[package]
name = "lircd"
version = "0.0.1"
authors = [ "Matthias Devlamynck <matthias.devlamynck@mailoo.org>" ]

[lib]
name = "lircd"

[[bin]]
name = "lircd"
doc = false

[dependencies]
mioco = "*"
env_logger = "*"
log = "*"
memchr = "*"
simple-signal = "*"
resolve = "*"
rustc-serialize = "*"
toml = "*"
docopt = { git = "https://github.com/mdevlamynck/docopt.rs.git" }

[dev-dependencies]
rand = "*"

[features]
unstable = []
