[package]
name = "lircd"
version = "0.0.1"
authors = [ "Matthias Devlamynck <matthias.devlamynck@mailoo.org>" ]

[lib]
name = "lircd"

[[bin]]
name = "lircd"
doc = false

[dependencies]
mioco = "*"
env_logger = "*"
log = "*"
memchr = "*"
simple-signal = "*"

[dev-dependencies]
rand = "*"

[features]
unstable = []
